[features]
seeds = false
skip-lint = false

[programs.localnet]
myepic_project = "8BmWcSGjjh91EhH4WM3JYwXgfSxfCti8esQpsHKq77E4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/diptendudas/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
